# Generated by Django 5.0.1 on 2024-02-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('string', 'String'), ('brass', 'Brass'), ('woodwind', 'Woodwind'), ('percussion', 'Percussion'), ('keyboard', 'Keyboard')], max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('repair', 'Needs Repair')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date_pick_up', models.DateField(default='')),
                ('date_returned', models.DateField(default='')),
                ('returned_condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('repair', 'Needs Repair')], default='used', max_length=50)),
                ('purchased', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.instruments')),
            ],
        ),
    ]
